Repository FEMessage/v-editor, pull requests merged in 2020-02, with the labels that each got.

#63 docs: 修改文档与删除无用文档
  docs/autosave.md
  docs/slot-loading.md
  src/mdParser.js
  src/v-editor.vue
Labels: documentation

#64 style: 使用 github markdown 样式
  README-zh.md
  README.md
  build/webpack.config.js
  package.json
  src/assets/maximize.svg
  src/assets/minimize.svg
  src/defaultEditorOptions.js
  src/plugin/FullScreen.js
  src/v-editor.vue
  styleguide.config.js
  yarn.lock
Labels: style

#66 docs: 添加插件开发指南链接
  README-zh.md
  README.md
Labels: documentation

#65 feat: 支持 md 图片语法
  src/plugin/ExtraFormat.js
  src/v-editor.vue
Labels: enhancement

#67 feat: 附件上传
  src/assets/attachment.svg
  src/defaultEditorOptions.js
  src/plugin/AttachmentUpload.js
  src/plugin/FullScreen.js
  src/plugin/ImageUploader.js
Labels: enhancement

#68 docs: 修改 readme
  README-zh.md
  README.md
Labels: documentation

#73 fix: 修复 v-model 传值问题
  package.json
  src/v-editor.vue
  yarn.lock
Labels: bug

#74 chore: 从 toolbar 移除 fontSize
  src/defaultEditorOptions.js
Labels: chore

#75 docs: 更新文档用例
  docs/editor-options.md
  docs/height.md
  docs/upload-options.md
Labels: documentation

#76 feat: 新增清除样式按钮
  .gitignore
  docs/basic.md
  package.json
  src/defaultEditorOptions.js
  src/plugin/RemoveFormat/RemoveFormat.js
  src/plugin/RemoveFormat/RemoveFormatLinks.js
  src/plugin/RemoveFormat/RemoveFormatUI.js
  styleguide/element.js
  yarn.lock
Labels: enhancement

#79 fix: 修复图片上传问题 & link 现在新标签页打开
  src/defaultEditorOptions.js
  src/plugin/ImageUploader.js
  src/utils/adapter.js
  src/v-editor.vue
Labels: bug

#80 feat: 支持 height 属性
  docs/height.md
  src/v-editor.vue
Labels: enhancement
